language: generic
matrix:
  include:
    - language: generic
      sudo: required
      services:
        - docker
      script: docker run -v $PWD:/walletcordova greenaddress/android_cordova@sha256:3e3353e63b9718fd21b312e2180a89db32280af433328a0a4bb426af60e88483

    - os: osx
      osx_image: xcode8.3
      before_script: sudo npm install -g cordova
      sudo: required
      install:
        - brew update > /dev/null
        - brew upgrade node
        - pip install virtualenv
      script:
        - ./prepare.sh
        - cordova prepare ios
        - cordova build ios

